name: Nightly builds

on:
  #          ┌───────────── minute (0 - 59)
  #          │  ┌───────────── hour (0 - 23)
  #          │  │ ┌───────────── day of the month (1 - 31)
  #          │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
  #          │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)                                  
  #          │  │ │ │ │
  #          │  │ │ │ │
  schedule: 
    - cron: "42 0 * * *"  # running every day at 0:42 UTC

  # Enable manual trigger
  workflow_dispatch:
    input:
      tags:
        description: "Tags to label this manual run (optional)"
        default: "Manual run"

# Automatically cancel previous workflows if a new one is executed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test Python ${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 40
    strategy:
      fail-fast: false
      max-parallel: 20 # Usage limits: https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration
      matrix:
        os: [ubuntu-22.04] # Available images: https://github.com/actions/runner-images/#available-images
        python: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - name: Checkout
      uses: actions/checkout@v3 # Info: https://github.com/actions/checkout
    
    - name: Python ${{ matrix.python }}
      uses: actions/setup-python@v4 # Info: https://github.com/actions/setup-python
      with:
        python-version: ${{ matrix.python }}

    - name: Install pre dependencies
      run: |
        python -m pip install -q --upgrade pip setuptools wheel      
        if [ "${{ matrix.python }}" == "3.8" ]; then
          echo "Installing pre-dependencies for Python 3.8"
          pip install "Cython<3.1" "numpy<2.0.0" "scipy<=1.13.1" "scikit-surprise<=1.1.3"
        fi  

    - name: Install dependencies
      run: |
        pip install -q -r requirements.txt

    - name: Python version and dependency list
      run: |
        echo "Python version expected: ${{ matrix.python }}"
        python --version
        which python
        pip list

    - name: Run functional tests
      run: |
        pip install -q "pytest>=3.6.4"
        pytest tests/functional --disable-warnings --durations 0
