name: PR gate

on:
  #          ┌───────────── minute (0 - 59)
  #          │  ┌───────────── hour (0 - 23)
  #          │  │ ┌───────────── day of the month (1 - 31)
  #          │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
  #          │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)                                  
  #          │  │ │ │ │
  #          │  │ │ │ │
  schedule: 
    - cron: "42 0 * * *"  # running every day at 0:42 UTC

  pull_request:
    # Only trigger the workflow with a PR to main
    branches:
    - main

  # Enable manual trigger
  workflow_dispatch:
    input:
      tags:
        description: "Tags to label this manual run (optional)"
        default: "Manual run"

# Automatically cancel previous workflows if a new one is executed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test Python ${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 40
    strategy:
      fail-fast: false
      max-parallel: 20 # Usage limits: https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration
      matrix:
        os: [ubuntu-22.04] # Available images: https://github.com/actions/runner-images/#available-images
        python: ["3.8", "3.9", "3.10"]

    steps:
    - name: Checkout
      uses: actions/checkout@v3 # Info: https://github.com/actions/checkout
    
    - name: Python ${{ matrix.python }}
      uses: actions/setup-python@v4 # Info: https://github.com/actions/setup-python
      with:
        python-version: ${{ matrix.python }}
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Python version and dependency list
      run: |
        echo "Python version expected: ${{ matrix.python }}"
        python --version
        which python
        pip list

    - name: Run tests
      run: |
        pytest tests --disable-warnings --durations 0